name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker organickarnali

    - name: Build Docker image
      run: |
        docker build -t organickarnali/${{ secrets.GCP_PROJECT_ID }}/organickarnali_backend:latest .
        docker push organickarnali/${{ secrets.GCP_PROJECT_ID }}/organickarnali_backend:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy organickarnali-backend --image organickarnali/${{ secrets.GCP_PROJECT_ID }}/organickarnali_backend:latest --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated --port 8080
